/**
 * CleanSlate Protocol — CSP Playground (v0.3)
 *
 * v0.3 Upgrade:
 * - Uses unified parseDocument() interface from parser.ts
 * - Agent-ready output via agent-adapter.ts
 * - Three output modes: CSP JSON / Markdown / AI Summary
 * - Streamlined pipeline: Upload → Parse → Display
 *
 * Design: Wabi-Sabi + Swiss Internationalism
 */

import { useState, useCallback, useRef } from "react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { motion, AnimatePresence } from "framer-motion";
import {
  FileText,
  Upload,
  Copy,
  Download,
  Check,
  ArrowLeft,
  X,
  FileType,
  Image as ImageIcon,
  Table,
  Presentation,
  File,
  Loader2,
  Layers,
  Shield,
  Hash,
  Clock,
  BarChart3,
  Globe,
  Zap,
  Bot,
  Sparkles,
} from "lucide-react";
import { parseDocument, type CSPOutput } from "@/lib/parser";
import { toAgentInput, toAgentSummaryPrompt, type AgentInput } from "@/lib/agent-adapter";

// ─── File type mapping ───
const FILE_TYPE_MAP: Record<string, { icon: typeof FileText; label: string }> = {
  "application/pdf": { icon: FileType, label: "PDF" },
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": { icon: FileText, label: "DOCX" },
  "text/html": { icon: FileText, label: "HTML" },
  "text/plain": { icon: FileText, label: "TXT" },
  "text/csv": { icon: Table, label: "CSV" },
  "application/json": { icon: FileText, label: "JSON" },
  "image/png": { icon: ImageIcon, label: "PNG" },
  "image/jpeg": { icon: ImageIcon, label: "JPEG" },
};

function getFileInfo(file: File) {
  const info = FILE_TYPE_MAP[file.type];
  if (info) return info;
  const ext = file.name.split(".").pop()?.toLowerCase() || "";
  if (["pdf"].includes(ext)) return { icon: FileType, label: "PDF" };
  if (["doc", "docx"].includes(ext)) return { icon: FileText, label: ext.toUpperCase() };
  if (["xls", "xlsx", "csv"].includes(ext)) return { icon: Table, label: ext.toUpperCase() };
  if (["ppt", "pptx"].includes(ext)) return { icon: Presentation, label: ext.toUpperCase() };
  if (["png", "jpg", "jpeg", "webp", "gif", "bmp"].includes(ext)) return { icon: ImageIcon, label: ext.toUpperCase() };
  if (["html", "htm"].includes(ext)) return { icon: FileText, label: "HTML" };
  if (["txt", "md", "json"].includes(ext)) return { icon: FileText, label: ext.toUpperCase() };
  return { icon: File, label: ext.toUpperCase() || "FILE" };
}

function formatFileSize(bytes: number): string {
  if (bytes === 0) return "0 B";
  const k = 1024;
  const sizes = ["B", "KB", "MB", "GB"];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(1))} ${sizes[i]}`;
}

// ─── AI Summary Generator (local, no API needed) ───
function generateAISummary(cspData: CSPOutput, agentInput: AgentInput): string {
  const sections = cspData.content.sections;
  const allEntities = sections.flatMap((s) => s.entities);
  const roles = Array.from(new Set(sections.map((s) => s.semantic_role)));

  // Build summary
  const lines: string[] = [];

  lines.push(`## AI Summary — ${cspData.metadata.title}`);
  lines.push("");
  lines.push(`> Generated by CleanSlate Agent Adapter v0.3`);
  lines.push(`> Protocol: ${cspData.verification.protocol_version} | Checksum: ${cspData.document.checksum.slice(0, 24)}...`);
  lines.push("");

  // Document overview
  lines.push("### Document Overview");
  lines.push("");
  lines.push(`| Property | Value |`);
  lines.push(`| --- | --- |`);
  lines.push(`| **Title** | ${cspData.metadata.title} |`);
  lines.push(`| **Type** | ${cspData.document.type} |`);
  lines.push(`| **Size** | ${formatFileSize(cspData.document.size_bytes)} |`);
  lines.push(`| **Language** | ${cspData.metadata.language} |`);
  if (cspData.metadata.page_count) {
    lines.push(`| **Pages** | ${cspData.metadata.page_count} |`);
  }
  lines.push(`| **Sections** | ${sections.length} |`);
  lines.push(`| **Tables Detected** | ${cspData.content.tables_detected} |`);
  lines.push(`| **Processing Time** | ${cspData.metadata.processing_time_ms}ms |`);
  lines.push("");

  // Semantic structure
  lines.push("### Semantic Structure");
  lines.push("");
  lines.push(`This document contains **${sections.length} sections** with the following semantic roles:`);
  lines.push("");

  const roleCounts: Record<string, number> = {};
  sections.forEach((s) => {
    roleCounts[s.semantic_role] = (roleCounts[s.semantic_role] || 0) + 1;
  });

  lines.push(`| Role | Count | Avg Confidence |`);
  lines.push(`| --- | --- | --- |`);
  for (const role of roles) {
    const roleSections = sections.filter((s) => s.semantic_role === role);
    const avgConf = roleSections.reduce((sum, s) => sum + s.confidence, 0) / roleSections.length;
    lines.push(`| \`${role}\` | ${roleCounts[role]} | ${(avgConf * 100).toFixed(1)}% |`);
  }
  lines.push("");

  // Key content preview
  lines.push("### Key Content Preview");
  lines.push("");

  const priorityRoles = ["summary", "introduction", "conclusion", "financial_data"];
  const keySection = sections.find((s) => priorityRoles.includes(s.semantic_role)) || sections[0];

  if (keySection) {
    lines.push(`**[${keySection.semantic_role}]** (confidence: ${(keySection.confidence * 100).toFixed(1)}%)`);
    lines.push("");
    lines.push(`> ${keySection.content.slice(0, 300)}${keySection.content.length > 300 ? "..." : ""}`);
    lines.push("");
  }

  // Entities
  if (allEntities.length > 0) {
    lines.push("### Extracted Entities");
    lines.push("");

    const entityByType: Record<string, string[]> = {};
    allEntities.forEach((e) => {
      if (!entityByType[e.type]) entityByType[e.type] = [];
      if (!entityByType[e.type].includes(e.value) && entityByType[e.type].length < 5) {
        entityByType[e.type].push(e.value);
      }
    });

    for (const [type, values] of Object.entries(entityByType)) {
      lines.push(`- **${type}**: ${values.join(", ")}`);
    }
    lines.push("");
  }

  // Agent-ready structure
  lines.push("### Agent Input Structure");
  lines.push("");
  lines.push("```json");
  lines.push(JSON.stringify(agentInput, null, 2).split("\n").slice(0, 20).join("\n"));
  if (JSON.stringify(agentInput, null, 2).split("\n").length > 20) {
    lines.push("  // ... (truncated for preview)");
  }
  lines.push("```");
  lines.push("");

  // Agent prompt preview
  lines.push("### Agent Prompt Preview");
  lines.push("");
  const prompt = toAgentSummaryPrompt(cspData);
  const promptLines = prompt.split("\n").slice(0, 10);
  lines.push("```");
  lines.push(promptLines.join("\n"));
  lines.push("// ... (full prompt available via toAgentSummaryPrompt())");
  lines.push("```");
  lines.push("");

  // Verification
  lines.push("### Verification");
  lines.push("");
  lines.push(`- **Merkle Root**: \`${cspData.verification.hash_tree}\``);
  lines.push(`- **Block Hashes**: ${cspData.verification.block_hashes.length} blocks`);
  lines.push(`- **Timestamp**: ${cspData.verification.timestamp}`);

  return lines.join("\n");
}

// ─── Main Converter Component ───
export default function Converter() {
  const [files, setFiles] = useState<File[]>([]);
  const [cspResults, setCspResults] = useState<Map<string, CSPOutput>>(new Map());
  const [agentResults, setAgentResults] = useState<Map<string, AgentInput>>(new Map());
  const [summaryResults, setSummaryResults] = useState<Map<string, string>>(new Map());
  const [converting, setConverting] = useState<Set<string>>(new Set());
  const [activeFile, setActiveFile] = useState<string | null>(null);
  const [isDragging, setIsDragging] = useState(false);
  const [copied, setCopied] = useState(false);
  const [outputMode, setOutputMode] = useState<"csp" | "markdown" | "summary">("csp");
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      setIsDragging(false);
      const droppedFiles = Array.from(e.dataTransfer.files);
      if (droppedFiles.length > 0) addFiles(droppedFiles);
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [files]
  );

  const addFiles = useCallback(
    async (newFiles: File[]) => {
      const updatedFiles = [...files, ...newFiles];
      setFiles(updatedFiles);
      if (!activeFile && newFiles.length > 0) setActiveFile(newFiles[0].name);

      for (const file of newFiles) {
        setConverting((prev) => new Set(prev).add(file.name));
        try {
          // v0.3: Use unified parseDocument interface
          const cspData = await parseDocument(file);
          setCspResults((prev) => new Map(prev).set(file.name, cspData));

          // Generate agent input
          const agentInput = toAgentInput(cspData);
          setAgentResults((prev) => new Map(prev).set(file.name, agentInput));

          // Generate AI summary
          const summary = generateAISummary(cspData, agentInput);
          setSummaryResults((prev) => new Map(prev).set(file.name, summary));

          toast.success(`${file.name} processed`, {
            description: `${cspData.content.sections.length} sections · ${cspData.content.tables_detected} tables · ${cspData.metadata.processing_time_ms}ms`,
          });
        } catch (error) {
          const errMsg = error instanceof Error ? error.message : "Unknown error";
          toast.error(`Failed to process ${file.name}`, { description: errMsg });
        } finally {
          setConverting((prev) => {
            const next = new Set(prev);
            next.delete(file.name);
            return next;
          });
        }
      }
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [files, activeFile]
  );

  const removeFile = useCallback(
    (filename: string) => {
      setFiles((prev) => prev.filter((f) => f.name !== filename));
      setCspResults((prev) => { const next = new Map(prev); next.delete(filename); return next; });
      setAgentResults((prev) => { const next = new Map(prev); next.delete(filename); return next; });
      setSummaryResults((prev) => { const next = new Map(prev); next.delete(filename); return next; });
      if (activeFile === filename) setActiveFile(files.find((f) => f.name !== filename)?.name || null);
    },
    [activeFile, files]
  );

  const getActiveOutput = useCallback(() => {
    if (!activeFile) return "";
    if (outputMode === "csp") {
      const csp = cspResults.get(activeFile);
      return csp ? JSON.stringify(csp, null, 2) : "";
    }
    if (outputMode === "markdown") {
      const csp = cspResults.get(activeFile);
      return csp?.content.markdown || "";
    }
    return summaryResults.get(activeFile) || "";
  }, [activeFile, outputMode, cspResults, summaryResults]);

  const copyToClipboard = useCallback(async () => {
    const output = getActiveOutput();
    if (!output) return;
    try {
      await navigator.clipboard.writeText(output);
      setCopied(true);
      toast.success("Copied to clipboard");
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error("Failed to copy");
    }
  }, [getActiveOutput]);

  const downloadOutput = useCallback(() => {
    const output = getActiveOutput();
    if (!output || !activeFile) return;
    const ext = outputMode === "csp" ? ".csp.json" : outputMode === "markdown" ? ".md" : ".summary.md";
    const mimeType = outputMode === "csp" ? "application/json" : "text/markdown";
    const blob = new Blob([output], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = activeFile.replace(/\.[^.]+$/, ext);
    a.click();
    URL.revokeObjectURL(url);
  }, [getActiveOutput, activeFile, outputMode]);

  const downloadAll = useCallback(() => {
    let content: string;
    let filename: string;
    let mimeType: string;
    if (outputMode === "csp") {
      const allCsp = Array.from(cspResults.values());
      content = JSON.stringify(allCsp, null, 2);
      filename = "cleanslate-output.csp.json";
      mimeType = "application/json";
    } else if (outputMode === "markdown") {
      content = Array.from(cspResults.entries())
        .map(([name, csp]) => `<!-- File: ${name} -->\n\n${csp.content.markdown}`)
        .join("\n\n---\n\n");
      filename = "cleanslate-output.md";
      mimeType = "text/markdown";
    } else {
      content = Array.from(summaryResults.entries())
        .map(([name, summary]) => `<!-- File: ${name} -->\n\n${summary}`)
        .join("\n\n---\n\n");
      filename = "cleanslate-summaries.md";
      mimeType = "text/markdown";
    }
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }, [outputMode, cspResults, summaryResults]);

  const currentOutput = getActiveOutput();
  const currentCsp = activeFile ? cspResults.get(activeFile) : null;
  const isConverting = activeFile ? converting.has(activeFile) : false;

  return (
    <div className="min-h-screen flex flex-col bg-background">
      {/* Header */}
      <header className="border-b border-border/50 backdrop-blur-sm bg-background/80 sticky top-0 z-50">
        <div className="container flex items-center justify-between h-14">
          <div className="flex items-center gap-3">
            <Link href="/">
              <span className="flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors">
                <ArrowLeft className="w-4 h-4" />
                <span className="text-sm font-sans">Back</span>
              </span>
            </Link>
            <div className="w-px h-5 bg-border" />
            <div className="flex items-center gap-2">
              <Layers className="w-4 h-4 text-primary" />
              <h1 className="text-lg font-serif font-semibold tracking-tight text-foreground">
                CSP Playground
              </h1>
              <span className="text-[9px] font-mono text-emerald-700 bg-emerald-50 border border-emerald-200/60 px-1.5 py-0.5 rounded">
                v0.3
              </span>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {cspResults.size > 1 && (
              <Button variant="outline" size="sm" onClick={downloadAll} className="text-xs bg-transparent">
                <Download className="w-3.5 h-3.5 mr-1.5" />
                Export All
              </Button>
            )}
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 flex flex-col lg:flex-row">
        {/* Left Panel - File List & Drop Zone */}
        <div className="w-full lg:w-80 xl:w-96 border-r border-border/50 flex flex-col bg-background/60">
          {/* Drop Zone */}
          <div
            className={`m-3 border-2 border-dashed rounded-lg transition-all duration-300 ${
              isDragging
                ? "border-primary bg-accent/50 scale-[0.98]"
                : "border-border/60 hover:border-primary/40"
            }`}
            onDragOver={(e) => { e.preventDefault(); setIsDragging(true); }}
            onDragLeave={() => setIsDragging(false)}
            onDrop={handleDrop}
            onClick={() => fileInputRef.current?.click()}
          >
            <div className="flex flex-col items-center justify-center py-8 px-4">
              <motion.div
                animate={isDragging ? { scale: 1.1, y: -4 } : { scale: 1, y: 0 }}
                transition={{ type: "spring", stiffness: 300, damping: 20 }}
              >
                <Upload className={`w-8 h-8 mb-3 transition-colors ${isDragging ? "text-primary" : "text-muted-foreground"}`} />
              </motion.div>
              <p className="text-sm font-medium text-foreground mb-1">Drop files here</p>
              <p className="text-xs text-muted-foreground text-center">
                PDF, HTML, CSV, TXT, JSON, Markdown
              </p>
            </div>
            <input
              ref={fileInputRef}
              type="file"
              multiple
              className="hidden"
              accept=".pdf,.html,.htm,.txt,.csv,.md,.json"
              onChange={(e) => {
                if (e.target.files) { addFiles(Array.from(e.target.files)); e.target.value = ""; }
              }}
            />
          </div>

          {/* Pipeline Indicator */}
          <div className="mx-3 mb-3 px-3 py-2 bg-secondary/30 rounded-md">
            <p className="text-[10px] font-mono text-muted-foreground/70 uppercase tracking-wider mb-1.5">Pipeline</p>
            <div className="flex items-center gap-1.5 text-[10px] font-mono text-muted-foreground">
              <span className="bg-amber-100 text-amber-700 px-1.5 py-0.5 rounded">Upload</span>
              <span className="text-muted-foreground/40">→</span>
              <span className="bg-blue-100 text-blue-700 px-1.5 py-0.5 rounded">parseDocument()</span>
              <span className="text-muted-foreground/40">→</span>
              <span className="bg-emerald-100 text-emerald-700 px-1.5 py-0.5 rounded">CSP JSON</span>
            </div>
          </div>

          {/* File List */}
          <div className="flex-1 overflow-y-auto px-3 pb-3">
            <AnimatePresence>
              {files.map((file) => {
                const info = getFileInfo(file);
                const Icon = info.icon;
                const isActive = activeFile === file.name;
                const isFileConverting = converting.has(file.name);
                const isDone = cspResults.has(file.name);
                const fileCsp = cspResults.get(file.name);

                return (
                  <motion.div
                    key={file.name}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: -20 }}
                    className={`group flex items-center gap-3 px-3 py-2.5 rounded-md mb-1 cursor-pointer transition-all ${
                      isActive ? "bg-accent text-accent-foreground" : "hover:bg-secondary/60"
                    }`}
                    onClick={() => setActiveFile(file.name)}
                  >
                    <div className="flex items-center justify-center w-8 h-8 rounded bg-secondary/80 shrink-0">
                      {isFileConverting ? (
                        <Loader2 className="w-4 h-4 animate-spin text-primary" />
                      ) : (
                        <Icon className="w-4 h-4 text-muted-foreground" />
                      )}
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium truncate">{file.name}</p>
                      <p className="text-xs text-muted-foreground">
                        {info.label} · {formatFileSize(file.size)}
                        {isDone && !isFileConverting && (
                          <span className="text-emerald-600"> · {fileCsp?.content.sections.length} sections</span>
                        )}
                      </p>
                    </div>
                    <button
                      onClick={(e) => { e.stopPropagation(); removeFile(file.name); }}
                      className="opacity-0 group-hover:opacity-100 transition-opacity p-1 hover:bg-destructive/10 rounded"
                    >
                      <X className="w-3.5 h-3.5 text-muted-foreground" />
                    </button>
                  </motion.div>
                );
              })}
            </AnimatePresence>

            {files.length === 0 && (
              <div className="flex flex-col items-center justify-center py-12 text-center">
                <Layers className="w-10 h-10 text-muted-foreground/40 mb-3" />
                <p className="text-sm text-muted-foreground">No files yet</p>
                <p className="text-xs text-muted-foreground/60 mt-1">
                  Drop documents to generate CSP output
                </p>
              </div>
            )}
          </div>
        </div>

        {/* Right Panel - Output */}
        <div className="flex-1 flex flex-col min-h-0">
          {activeFile && currentOutput ? (
            <>
              {/* Quality Metrics Bar */}
              {currentCsp && (
                <div className="border-b border-border/30 bg-emerald-50/30 px-4 py-2">
                  <div className="flex items-center gap-4 text-xs flex-wrap">
                    <div className="flex items-center gap-1.5 text-emerald-700">
                      <Zap className="w-3 h-3" />
                      <span className="font-mono font-medium">v0.3 Engine</span>
                    </div>
                    <div className="w-px h-3.5 bg-emerald-200" />
                    <div className="flex items-center gap-1 text-muted-foreground">
                      <Clock className="w-3 h-3" />
                      <span className="font-mono">{currentCsp.metadata.processing_time_ms}ms</span>
                    </div>
                    {currentCsp.metadata.page_count && (
                      <div className="flex items-center gap-1 text-muted-foreground">
                        <FileText className="w-3 h-3" />
                        <span className="font-mono">{currentCsp.metadata.page_count} pages</span>
                      </div>
                    )}
                    <div className="flex items-center gap-1 text-muted-foreground">
                      <BarChart3 className="w-3 h-3" />
                      <span className="font-mono">{currentCsp.content.total_lines} lines</span>
                    </div>
                    <div className="flex items-center gap-1 text-muted-foreground">
                      <Table className="w-3 h-3" />
                      <span className="font-mono">{currentCsp.content.tables_detected} tables</span>
                    </div>
                    <div className="flex items-center gap-1 text-muted-foreground">
                      <Layers className="w-3 h-3" />
                      <span className="font-mono">{currentCsp.content.sections.length} sections</span>
                    </div>
                    <div className="flex items-center gap-1 text-muted-foreground">
                      <Globe className="w-3 h-3" />
                      <span className="font-mono">{currentCsp.metadata.language}</span>
                    </div>
                  </div>
                </div>
              )}

              {/* Output Header */}
              <div className="border-b border-border/50 bg-background/60 backdrop-blur-sm px-4 py-2.5">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => setOutputMode("csp")}
                      className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-all ${
                        outputMode === "csp"
                          ? "bg-primary/10 text-primary border border-primary/20"
                          : "text-muted-foreground hover:text-foreground hover:bg-secondary/50"
                      }`}
                    >
                      <Hash className="w-3 h-3" />
                      CSP JSON
                    </button>
                    <button
                      onClick={() => setOutputMode("markdown")}
                      className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-all ${
                        outputMode === "markdown"
                          ? "bg-primary/10 text-primary border border-primary/20"
                          : "text-muted-foreground hover:text-foreground hover:bg-secondary/50"
                      }`}
                    >
                      <FileText className="w-3 h-3" />
                      Markdown
                    </button>
                    <button
                      onClick={() => setOutputMode("summary")}
                      className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-all ${
                        outputMode === "summary"
                          ? "bg-violet-500/10 text-violet-600 border border-violet-200/40"
                          : "text-muted-foreground hover:text-foreground hover:bg-secondary/50"
                      }`}
                    >
                      <Sparkles className="w-3 h-3" />
                      AI Summary
                    </button>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <Button variant="outline" size="sm" onClick={copyToClipboard} className="h-7 text-xs bg-transparent">
                      {copied ? <Check className="w-3.5 h-3.5 mr-1 text-green-600" /> : <Copy className="w-3.5 h-3.5 mr-1" />}
                      {copied ? "Copied" : "Copy"}
                    </Button>
                    <Button variant="outline" size="sm" onClick={downloadOutput} className="h-7 text-xs bg-transparent">
                      <Download className="w-3.5 h-3.5 mr-1" />
                      {outputMode === "csp" ? ".csp.json" : ".md"}
                    </Button>
                  </div>
                </div>
              </div>

              {/* Output Content */}
              <div className="flex-1 overflow-auto">
                {outputMode === "csp" && currentCsp ? (
                  <CSPViewer csp={currentCsp} />
                ) : outputMode === "summary" ? (
                  <div className="p-6 max-w-3xl mx-auto">
                    <div className="flex items-center gap-2 mb-4 pb-3 border-b border-violet-200/40">
                      <Bot className="w-5 h-5 text-violet-500" />
                      <span className="text-sm font-medium text-violet-700">Agent-Ready Analysis</span>
                    </div>
                    <MarkdownPreview content={currentOutput} />
                  </div>
                ) : (
                  <div className="p-6 max-w-3xl mx-auto">
                    <MarkdownPreview content={currentOutput} />
                  </div>
                )}
              </div>
            </>
          ) : isConverting ? (
            <div className="flex-1 flex items-center justify-center">
              <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="text-center">
                <Loader2 className="w-8 h-8 animate-spin text-primary mx-auto mb-3" />
                <p className="text-sm text-muted-foreground">Processing with v0.3 engine...</p>
                <p className="text-xs text-muted-foreground/60 mt-1">parseDocument() → CSP Schema → Agent Adapter</p>
              </motion.div>
            </div>
          ) : (
            <div className="flex-1 flex items-center justify-center">
              <div className="text-center max-w-md">
                <div className="w-16 h-16 rounded-full bg-secondary/50 flex items-center justify-center mx-auto mb-4">
                  <Layers className="w-7 h-7 text-muted-foreground/50" />
                </div>
                <h3 className="font-serif text-lg text-foreground mb-2">CSP Playground v0.3</h3>
                <p className="text-sm text-muted-foreground leading-relaxed mb-4">
                  Drop documents on the left panel. The unified parser generates structured CSP output that AI agents can directly consume.
                </p>
                <div className="bg-secondary/30 rounded-lg p-4 text-left">
                  <p className="text-[10px] font-mono text-muted-foreground/70 uppercase tracking-wider mb-2">v0.3 Pipeline</p>
                  <div className="space-y-1.5 text-xs font-mono text-muted-foreground">
                    <div className="flex items-center gap-2">
                      <span className="w-4 text-center text-amber-600">1</span>
                      <span>Upload document (PDF, HTML, CSV, TXT, JSON)</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="w-4 text-center text-blue-600">2</span>
                      <span>parseDocument() → CSP Schema</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="w-4 text-center text-emerald-600">3</span>
                      <span>View: CSP JSON / Markdown / AI Summary</span>
                    </div>
                  </div>
                </div>
                <div className="flex flex-wrap justify-center gap-2 text-[10px] font-mono text-muted-foreground/60 mt-4">
                  <span className="bg-secondary/50 px-2 py-0.5 rounded">parseDocument()</span>
                  <span className="bg-secondary/50 px-2 py-0.5 rounded">toAgentInput()</span>
                  <span className="bg-secondary/50 px-2 py-0.5 rounded">CSP Schema v1.0</span>
                  <span className="bg-secondary/50 px-2 py-0.5 rounded">Verification Layer</span>
                </div>
              </div>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}

// ─── CSP Structured Viewer ───
function CSPViewer({ csp }: { csp: CSPOutput }) {
  return (
    <div className="p-6 max-w-4xl mx-auto space-y-6">
      {/* Document Header */}
      <div className="bg-card border border-border/40 rounded-lg p-5">
        <div className="flex items-center gap-2 mb-3">
          <Layers className="w-4 h-4 text-primary" />
          <span className="text-xs font-mono text-primary/70 uppercase tracking-wider">CSP Document</span>
          <span className="text-[10px] font-mono text-muted-foreground/60 ml-auto">v{csp.metadata.parser_version}</span>
        </div>
        <h2 className="font-serif text-xl font-semibold mb-2">{csp.document.filename}</h2>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
          <div>
            <span className="text-muted-foreground">Type</span>
            <p className="font-mono font-medium text-foreground">{csp.document.type.split("/").pop()?.toUpperCase() || "UNKNOWN"}</p>
          </div>
          <div>
            <span className="text-muted-foreground">Size</span>
            <p className="font-mono font-medium text-foreground">{formatFileSize(csp.document.size_bytes)}</p>
          </div>
          <div>
            <span className="text-muted-foreground">Sections</span>
            <p className="font-mono font-medium text-foreground">{csp.content.sections.length}</p>
          </div>
          <div>
            <span className="text-muted-foreground">Language</span>
            <p className="font-mono font-medium text-foreground">{csp.metadata.language}</p>
          </div>
        </div>
        <div className="mt-3 pt-3 border-t border-border/30 flex items-center gap-4 text-[10px] font-mono text-muted-foreground/70">
          <span>Parser v{csp.metadata.parser_version}</span>
          <span>{csp.metadata.processing_time_ms}ms</span>
          <span>{csp.content.tables_detected} tables</span>
          <span>{csp.content.total_lines} lines</span>
          <span className="ml-auto text-muted-foreground/50">{csp.metadata.document_id.slice(0, 8)}...</span>
        </div>
      </div>

      {/* Layer 1: Document */}
      <div className="bg-amber-50/50 border border-amber-200/40 rounded-lg p-5">
        <div className="flex items-center gap-2 mb-3">
          <div className="w-5 h-5 rounded bg-amber-100 flex items-center justify-center">
            <FileText className="w-3 h-3 text-amber-700" />
          </div>
          <span className="text-xs font-mono text-amber-700/70 uppercase tracking-wider">Document Layer</span>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
          <div>
            <span className="text-amber-700/60">Checksum</span>
            <p className="font-mono text-amber-900 break-all">{csp.document.checksum.slice(0, 32)}...</p>
          </div>
          <div>
            <span className="text-amber-700/60">Content Length</span>
            <p className="font-mono text-amber-900">{csp.content.markdown.length.toLocaleString()} chars</p>
          </div>
          <div>
            <span className="text-amber-700/60">Pages</span>
            <p className="font-mono text-amber-900">{csp.metadata.page_count || "N/A"}</p>
          </div>
        </div>
      </div>

      {/* Layer 2: Content / Semantic */}
      <div className="bg-blue-50/50 border border-blue-200/40 rounded-lg p-5">
        <div className="flex items-center gap-2 mb-3">
          <div className="w-5 h-5 rounded bg-blue-100 flex items-center justify-center">
            <Layers className="w-3 h-3 text-blue-700" />
          </div>
          <span className="text-xs font-mono text-blue-700/70 uppercase tracking-wider">Content — Semantic Sections</span>
        </div>

        {/* Entity Summary */}
        {csp.content.sections.some((s) => s.entities.length > 0) && (
          <div className="flex flex-wrap gap-2 mb-4">
            {(() => {
              const entitySummary: Record<string, number> = {};
              csp.content.sections.forEach((s) =>
                s.entities.forEach((e) => {
                  entitySummary[e.type] = (entitySummary[e.type] || 0) + 1;
                })
              );
              return Object.entries(entitySummary).map(([type, count]) => (
                <span key={type} className="text-[10px] font-mono bg-blue-100/60 text-blue-800 px-2 py-0.5 rounded">
                  {type}: {count}
                </span>
              ));
            })()}
          </div>
        )}

        {/* Sections */}
        <div className="space-y-2">
          {csp.content.sections.map((section) => (
            <div key={section.id} className="bg-white/60 border border-blue-100/60 rounded-md p-3">
              <div className="flex items-center gap-2 mb-1.5">
                <span className="text-[10px] font-mono text-blue-500">{section.id}</span>
                <span className="text-[10px] font-mono bg-blue-100 text-blue-700 px-1.5 py-0.5 rounded">
                  {section.semantic_role}
                </span>
                <span className="text-[10px] font-mono text-blue-400 ml-auto">
                  L{section.level} · {section.confidence.toFixed(2)}
                </span>
              </div>
              <p className="text-xs text-blue-900/80 leading-relaxed line-clamp-3">
                {section.content}
              </p>
              {section.entities.length > 0 && (
                <div className="flex flex-wrap gap-1 mt-2">
                  {section.entities.map((entity, i) => (
                    <span key={i} className="text-[9px] font-mono bg-blue-50 border border-blue-100 text-blue-600 px-1.5 py-0.5 rounded">
                      {entity.type}: {entity.value}
                    </span>
                  ))}
                </div>
              )}
            </div>
          ))}
          {csp.content.sections.length === 0 && (
            <p className="text-xs text-blue-500/60 italic">No semantic sections extracted</p>
          )}
        </div>
      </div>

      {/* Layer 3: Verification */}
      <div className="bg-slate-50/50 border border-slate-200/40 rounded-lg p-5">
        <div className="flex items-center gap-2 mb-3">
          <div className="w-5 h-5 rounded bg-slate-100 flex items-center justify-center">
            <Shield className="w-3 h-3 text-slate-700" />
          </div>
          <span className="text-xs font-mono text-slate-700/70 uppercase tracking-wider">Verification Layer</span>
        </div>
        <div className="space-y-3 text-xs">
          <div>
            <span className="text-slate-500">Merkle Root</span>
            <p className="font-mono text-slate-800 break-all">{csp.verification.hash_tree}</p>
          </div>
          <div>
            <span className="text-slate-500">Block Hashes ({csp.verification.block_hashes.length})</span>
            <div className="flex flex-wrap gap-1 mt-1">
              {csp.verification.block_hashes.map((hash, i) => (
                <span key={i} className="font-mono text-[9px] bg-slate-100 text-slate-600 px-1.5 py-0.5 rounded">
                  {hash}
                </span>
              ))}
            </div>
          </div>
          <div className="flex gap-6">
            <div>
              <span className="text-slate-500">Protocol</span>
              <p className="font-mono text-slate-800">{csp.verification.protocol_version}</p>
            </div>
            <div>
              <span className="text-slate-500">Timestamp</span>
              <p className="font-mono text-slate-800">{csp.verification.timestamp}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// ─── Markdown Preview ───
function MarkdownPreview({ content }: { content: string }) {
  const lines = content.split("\n");
  const elements: React.ReactNode[] = [];
  let inCodeBlock = false;
  let codeContent = "";
  let codeLang = "";
  let inTable = false;
  let tableRows: string[][] = [];

  const flushTable = () => {
    if (tableRows.length > 0) {
      elements.push(
        <div key={`table-${elements.length}`} className="overflow-x-auto my-4 border border-border/40 rounded-lg">
          <table className="min-w-full text-sm border-collapse">
            <thead>
              <tr className="bg-secondary/40">
                {tableRows[0].map((cell, i) => (
                  <th key={i} className="px-3 py-2 text-left font-semibold text-foreground border-b border-border/50 whitespace-nowrap">{renderInline(cell)}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {tableRows.slice(1).map((row, ri) => (
                <tr key={ri} className={ri % 2 === 0 ? "" : "bg-secondary/20"}>
                  {row.map((cell, ci) => (
                    <td key={ci} className="px-3 py-2 text-foreground/80 border-b border-border/30 whitespace-nowrap">{renderInline(cell)}</td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      );
      tableRows = [];
    }
    inTable = false;
  };

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line.startsWith("```")) {
      if (inCodeBlock) {
        elements.push(
          <div key={`code-${i}`} className="my-3 rounded-lg overflow-hidden border border-border/40">
            {codeLang && (
              <div className="bg-secondary/60 px-3 py-1 text-[10px] font-mono text-muted-foreground border-b border-border/30">
                {codeLang}
              </div>
            )}
            <pre className="bg-secondary/30 p-4 overflow-x-auto text-sm font-mono text-foreground/80">
              {codeContent.trim()}
            </pre>
          </div>
        );
        codeContent = "";
        codeLang = "";
        inCodeBlock = false;
      } else {
        flushTable();
        inCodeBlock = true;
        codeLang = line.slice(3).trim();
      }
      continue;
    }
    if (inCodeBlock) { codeContent += line + "\n"; continue; }
    if (line.startsWith("|") && line.endsWith("|")) {
      const cells = line.split("|").slice(1, -1).map((c) => c.trim());
      if (cells.every((c) => /^[-:]+$/.test(c))) { inTable = true; continue; }
      tableRows.push(cells);
      if (!inTable && tableRows.length > 1) inTable = true;
      continue;
    } else if (inTable) { flushTable(); }

    if (line.startsWith("# ")) elements.push(<h1 key={i} className="text-2xl font-serif font-bold mt-6 mb-3 text-foreground">{renderInline(line.slice(2))}</h1>);
    else if (line.startsWith("## ")) elements.push(<h2 key={i} className="text-xl font-serif font-semibold mt-5 mb-2 text-foreground border-b border-border/30 pb-1">{renderInline(line.slice(3))}</h2>);
    else if (line.startsWith("### ")) elements.push(<h3 key={i} className="text-lg font-serif font-semibold mt-4 mb-2 text-foreground">{renderInline(line.slice(4))}</h3>);
    else if (line.startsWith("#### ")) elements.push(<h4 key={i} className="text-base font-sans font-semibold mt-3 mb-1.5 text-foreground">{renderInline(line.slice(5))}</h4>);
    else if (line.startsWith("> ")) elements.push(<blockquote key={i} className="border-l-3 border-primary/40 pl-4 my-3 text-muted-foreground italic">{renderInline(line.slice(2))}</blockquote>);
    else if (line === "---" || line === "***") elements.push(<hr key={i} className="my-4 border-border/50" />);
    else if (line.match(/^[-*] /)) elements.push(<div key={i} className="flex gap-2 my-0.5 ml-2"><span className="text-primary mt-1.5 text-xs">•</span><span className="text-foreground/80 text-sm">{renderInline(line.slice(2))}</span></div>);
    else if (line.match(/^\d+\. /)) {
      const match = line.match(/^(\d+)\. (.*)$/);
      if (match) elements.push(<div key={i} className="flex gap-2 my-0.5 ml-2"><span className="text-primary text-sm font-medium min-w-[1.2rem]">{match[1]}.</span><span className="text-foreground/80 text-sm">{renderInline(match[2])}</span></div>);
    }
    else if (line.startsWith("<!--")) { /* skip comments */ }
    else if (line.trim() === "") elements.push(<div key={i} className="h-2" />);
    else elements.push(<p key={i} className="text-sm text-foreground/80 leading-relaxed my-1">{renderInline(line)}</p>);
  }
  flushTable();
  return <>{elements}</>;
}

function renderInline(text: string): React.ReactNode {
  const parts: React.ReactNode[] = [];
  let remaining = text;
  let key = 0;
  while (remaining.length > 0) {
    const boldMatch = remaining.match(/\*\*(.+?)\*\*/);
    if (boldMatch && boldMatch.index !== undefined) {
      if (boldMatch.index > 0) parts.push(<span key={key++}>{remaining.slice(0, boldMatch.index)}</span>);
      parts.push(<strong key={key++} className="font-semibold text-foreground">{boldMatch[1]}</strong>);
      remaining = remaining.slice(boldMatch.index + boldMatch[0].length);
      continue;
    }
    const codeMatch = remaining.match(/`(.+?)`/);
    if (codeMatch && codeMatch.index !== undefined) {
      if (codeMatch.index > 0) parts.push(<span key={key++}>{remaining.slice(0, codeMatch.index)}</span>);
      parts.push(<code key={key++} className="bg-secondary/80 px-1.5 py-0.5 rounded text-xs font-mono">{codeMatch[1]}</code>);
      remaining = remaining.slice(codeMatch.index + codeMatch[0].length);
      continue;
    }
    const italicMatch = remaining.match(/\*(.+?)\*/);
    if (italicMatch && italicMatch.index !== undefined) {
      if (italicMatch.index > 0) parts.push(<span key={key++}>{remaining.slice(0, italicMatch.index)}</span>);
      parts.push(<em key={key++}>{italicMatch[1]}</em>);
      remaining = remaining.slice(italicMatch.index + italicMatch[0].length);
      continue;
    }
    parts.push(<span key={key++}>{remaining}</span>);
    break;
  }
  return parts.length === 1 ? parts[0] : <>{parts}</>;
}
